version: '3'
services:
    mongo:
        container_name: 'mongo'
        image: 'mongo:latest'
        ports:
            - "27017:27017"
        volumes:
            - ./.database/data:/data/db
        # volumes:
        #     - type: volume
        #     source: mongodb_data_volume
        #     target: /data/db

    mongo-credentials:
        container_name: 'mongo-credentials'
        image: 'mongo:latest'
        ports:
            - "27018:27017"
        volumes:
            - ./.database/cred:/data/db
        # volumes: ./mongo/cred:/data/db
        # volumes:
        #     - type: volume
        #     source: mongodb_cred_volume
        #     target: /data/db



    # redis:
    #     container_name: 'redis'
    #     image: redis:latest
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - ./config/redis.conf:/redis.conf
    #     command: [ "redis-server", "/redis.conf" ]

    operations-api:
        container_name: 'operations-api'
        build: './operations api'
        ports:
            - '5000:5000'
        depends_on:
            - 'mongo'

    login-api:
        container_name: 'login-api'
        build: './login api'
        ports:
            - '5002:5002'
        depends_on:
            - 'mongo-credentials'

    firewall-api:
        container_name: 'firewall-api'
        build: './firewall api'
        ports:
            - '5003:5003'
        depends_on:
            - 'login-api'

    # web:
    #     container_name: 'web'
    #     build: './web'
    #     ports:
    #         - '8081:80'
    #         - '8082:4200'
    #     depends_on:
    #         - operations-api
    #     tty: true
    #     links:
    #         - operations-api

# volumes:
#     mongodb_cred_volume:
#         external: true
#     mongodb_data_volume:
#         external: true