version: '3'
services:
    mongo:
        container_name: 'mongo'
        image: 'mongo:latest'
        ports:
            - "27017:27017"

    mongo-credentials:
        container_name: 'mongo-credentials'
        image: 'mongo:latest'
        ports:
            - "27018:27017"

    # redis:
    #     container_name: 'redis'
    #     image: redis:latest
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - ./config/redis.conf:/redis.conf
    #     command: [ "redis-server", "/redis.conf" ]

    operations-api:
        container_name: 'operations-api'
        build: './operations api'
        ports:
            - '5000:5000'
        depends_on:
            - 'mongo'

    # auth-api:
    #     container_name: 'auth-api'
    #     build: './auth'
    #     ports:
    #         - '5001:5001'
    #     depends_on:
    #         - 'redis'

    login-api:
        container_name: 'login-api'
        build: './login api'
        ports:
            - '5002:5002'
        depends_on:
            - 'mongo-credentials'

    firewall-api:
        container_name: 'firewall-api'
        build: './firewall api'
        ports:
            - '5003:5003'
        depends_on:
            - 'login-api'

    # web:
    #     container_name: 'web'
    #     build: './web'
    #     ports:
    #         - '8081:80'
    #         - '8082:4200'
    #     depends_on:
    #         - operations-api
    #     tty: true
    #     links:
    #         - operations-api